POST http://localhost:3003/api/posts/63792327b717d4f51dd52bb2/comments HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkBUZXN0IiwiaWQiOiI2MmU3MmE2YjVjN2UxNWFjNDA2M2IwODEiLCJpYXQiOjE2NTk0MDkzNjl9.U1KEbcsihhe37bYqZGObtZRD1KIXpWlcEU7skrhQ-yo

{
    "text": "This is another comment test",
    "post": "63792327b717d4f51dd52bb2",
    "user": "63791ff3abcf3c980242c398"
  }